services:
  - type: static
    name: vgatk-bd
    repo: https://github.com/artembykov546-code/vgatk_bd.git # Укажите ссылку на ваш репо
    branch: main
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /images/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /css/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /js/*
        name: Cache-Control
        value: public, max-age=31536000, immutable