services:
  - type: static
    name: vgatk-bd
    publishDir: dist
    buildCommand: echo "✅ Используем готовую сборку из папки dist"
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html