services:
  - type: web
    name: vgatk-bd
    runtime: node
    plan: free
    buildCommand: bash render-build.sh
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: SUPABASE_URL
        value: https://selbolepupendprhixas.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlbGJvbGVwdXBlbmRwcmhpeGFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI1NjQzODgsImV4cCI6MjA5ODE0MDM4OH0.UpWEr6hEs9ytnDxnaQ7Uf3d_xDQLHO-eejkIw53o7EE